### ISSUE TITLE
Django docs crash with `AttributeError: 'DirectiveAdapter' object has no attribute 'env'``

### ISSUE THREAD

**Issue by timgraham** [sphinx-doc/sphinx#4885]
After upgrading from Sphinx 1.7.2 to 1.7.3, building [Django's docs](https://github.com/django/django/) fails with:
```
Exception occurred:
  File "/home/jenkins/workspace/docs/tests/.env/lib/python3.4/site-packages/sphinx/domains/python.py", line 568, in run
    (modname, self.env.doc2path(modules[modname])),
AttributeError: 'DirectiveAdapter' object has no attribute 'env'`
```
Bisected to f4f693eff7b081785cc5704a6ff22cf0371355f3.

**Comment by tk0miya** [comment]
Fixed by #4887.
Thank you for @knorth55 !
