### PR TITLE
intersphinx: Don't warn about pure-duplicate ambiguous definitions when loading 'objects.inv' entries.

### LINKED ISSUE #12585: Warning about duplicate definitions in intersphinx mapping
### Describe the bug

We recently started getting warnings about duplicate definition in intersphinx, from two upstream projects:

- sklearn, see https://github.com/scikit-learn/scikit-learn/issues/29337
- ipywidgets, see https://github.com/jupyter-widgets/ipywidgets/issues/3930

Sklearn maintainers suspect this to be a sphinx bug, so I am opening this issue here.

### How to Reproduce
```
$ pip list | grep  Sphinx
Sphinx                        7.4.2
$ python -m sphinx.ext.intersphinx https://scikit-learn.org/stable/objects.inv | grep "    y "
WARNING:sphinx.sphinx.util.inventory:inventory <> contains multiple definitions for std:term:y
    y        
```

and
```
$ python -m sphinx.ext.intersphinx https://ipywidgets.readthedocs.io/en/stable/objects.inv | grep 'Widget Layout.ipynb#display'
WARNING:sphinx.sphinx.util.inventory:inventory <> contains multiple definitions for std:label:examples/Widget Layout.ipynb#display
    examples/Widget Layout.ipynb#display     display                                 : examples/Widget%20Layout.html#id1
```

### Environment Information

```text
Sphinx 7.4.2
```

### Sphinx extensions

```python
intersphinx
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayaddison**
### Feature or Bugfix
- Bugfix

### Purpose
- Don't emit a warning _at inventory load time_ if two ambiguously-resolved Intersphinx `objects.inv` entries resolve to exactly the same result (i.e. are duplicates that differ only by lowercase/uppercase characters).

### Detail
- ~~Use `set`-comparison of the reference fields.~~ 
- Do log a `debug` message for reference.

### Todo / open questions
- [ ] Also handle a [similar scenario in some Intersphinx entity resolution code](https://github.com/sphinx-doc/sphinx/issues/12585#issuecomment-2228518109) introduced at the same time?
  - TBD.  Moved to separate PR #12587. 

### Relates
- Warning introduced in #12329.
- Resolves #12585.

Edit: clarify the false-positive warning that is filtered by this branch.

### CODE REVIEW

**Comment by jayaddison** [comment]
> * Use `set`-comparison of the reference fields.

Perhaps direct tuple-to-tuple comparison is better in this case; I'm checking that currently.

File: sphinx/util/inventory.py [hunk 1]
```diff
@@ -154,11 +154,16 @@ def load_v2(
                 # Some types require case insensitive matches:
                 # * 'term': https://github.com/sphinx-doc/sphinx/issues/9291
                 # * 'label': https://github.com/sphinx-doc/sphinx/issues/12008
-                definition = f"{type}:{name}"
-                if definition.lower() in potential_ambiguities:
-                    actual_ambiguities.add(definition)
+                definition, content = f"{type}:{name}", (prio, location, dispname)
```
Comment (AA-Turner) [inline sphinx/util/inventory.py]:
```suggestion
                definition = f"{type}:{name}"
                content = prio, location, dispname
```

File: sphinx/util/inventory.py [hunk 2]
```diff
@@ -126,7 +126,7 @@ def load_v2(
         invdata: Inventory = {}
         projname = stream.readline().rstrip()[11:]
         version = stream.readline().rstrip()[11:]
-        potential_ambiguities = set()
+        potential_ambiguities: dict[str, tuple[str, str, str]] = {}
```
Comment (AA-Turner) [inline sphinx/util/inventory.py:130]:
```suggestion
        # definition -> priority, location, display name
        potential_ambiguities: dict[str, tuple[str, str, str]] = {}
```

**Comment by AA-Turner** [comment]
Oh, this should have had a CHANGES entry...

A

**Comment by jayaddison** [comment]
> Oh, this should have had a CHANGES entry...

"Reduce log severity of detected ambiguous Intersphinx inventory items that are found to be case-insensitive duplicates." ?

**Comment by jayaddison** [comment]
(rationale: they _are_ still resolved ambiguously, but since they're duplicates, they're basically innocuous)

**Comment by AA-Turner** [comment]
Added a variant of that as 12064e05b.

A

**Comment by jayaddison** [comment]
Thank you!
