### ISSUE TITLE
Problem with sphinx_jsondomain

### ISSUE THREAD

**Issue by matemax** [sphinx-doc/sphinx#3685]
### Problem
- sphinx-jsondomain not working in version 1.5.5 (working in 1.5.0)

#### Procedure to reproduce the problem

Insall sphinx-jsondomain (pip install -q sphinx-jsondomain) and compile example
```
        .. json:object:: Github User
            :showexample:

            :property user_name login: the user's unique login
```
This does't seem like bug of sphinx-jsondomain because this not working in new version of  sphinx . 

 
#### Error logs / results
```
  File "C:\Python36\lib\site-packages\sphinx\util\docfields.py", line 314, in transform
    content, env=self.directive.env)
AttributeError: 'DirectiveAdapter' object has no attribute 'env'
```

### Environment info
- OS: Windows
- Python version: 3.6
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 87b30cc.
