### ISSUE TITLE
AttributeError: 'DirectiveAdapter' object has no attribute 'get_field_type_map' since v2.1.0

### ISSUE THREAD

**Issue by p12tic** [sphinx-doc/sphinx#6474]
**Describe the bug**
I get this error since v2.1.0:

`AttributeError: 'DirectiveAdapter' object has no attribute 'get_field_type_map' since v2.1.0`.

The issue has been bisected to PR #6192.

**To Reproduce**

```
git clone https://github.com/buildbot/buildbot
cd buildbot
make virtualenv
source .venv/bin/activate
<edit requirements-cidocs.txt to use Sphinx==2.1.0 or newer>
pip install -r requirements-ci.txt
pip install -r requirements-cidocs.txt
make docs
```

**Expected behavior**
No error.

**Your project**
https://github.com/buildbot/buildbot

**Screenshots**
(none)

**Environment info**
- OS: Kubuntu 18.04
- Python version: 3.6.7
- Sphinx version: 2.1.0
- Sphinx extensions:
sphinx-jinja==1.1.0
sphinxcontrib-blockdiag==1.5.5
sphinxcontrib-spelling==4.2.1
sphinxcontrib-websupport==1.1.2

**Additional context**
(none)

**Comment by p12tic** [comment]
Attached full traceback: [sphinx-err-zlejo3ha.log](https://github.com/sphinx-doc/sphinx/files/3278089/sphinx-err-zlejo3ha.log)

**Comment by tk0miya** [comment]
It seems the error was raised inside `bbdocs/ext.py`.
```
  File "/home/p12/code/my/checkouts/buildbot/master/docs/bbdocs/ext.py", line 97, in run
    DocFieldTransformer(self).transform_all(contentnode)
  File "/home/p12/code/my/checkouts/buildbot/.venv/lib/python3.6/site-packages/sphinx/util/docfields.py", line 252, in __init__
    self.typemap = directive.get_field_type_map()
AttributeError: 'DirectiveAdapter' object has no attribute 'get_field_type_map'
```

And it uses `DocFieldTransformer` for non `ObjectDescription` subclasses. That is very tricky code to me...

**Comment by p12tic** [comment]
Hm, thanks for pointing this out. I'll see whether this is possible to fix on our side.

**Comment by abompard** [comment]
I'm having the same issue with the `cornice_sphinx` extension, because it adds a directive that isn't a subclass of `ObjectDescription`. Since the `get_field_type_map` method is called by the `DocFieldTransformer` unconditionnaly, maybe the method should be moved to the `SphinxDirective` superclass. Or the `DocFieldTransformer` could catch that exception and set `typemap` to `{}` instead.

**Comment by tk0miya** [comment]
I object to move `get_field_type_map()` to `SphinxDirective` because field type map is not a property of standard directives. They are only for `ObjectDescription`.
But I can accept another idea:

> Or the DocFieldTransformer could catch that exception and set typemap to {} instead.

So reopen this again.

**Comment by tk0miya** [comment]
I just posted #6624. Could you check this please?

Note: this does not mean `DocFieldTransformer` will accept standard directives in future. This only keeps compatibility with past versions.

**Comment by tk0miya** [comment]
Fixed by #6624 .
Thank you for comment.
Closing again.
