### ISSUE TITLE
AttributeError: 'Symbol' object has no attribute 'identOrOp' after upgrade of Sphinx from version 1.6.5 to 1.7.5

### ISSUE THREAD

**Issue by krzychb** [sphinx-doc/sphinx#5039]
Subject: Exception is dropped during compilation after upgrade of Sphinx from version 1.6.5 to 1.7.5 on the following projects:

https://github.com/espressif/esp-idf/tree/master/docs/en
https://github.com/espressif/esp-adf/tree/master/docs/en

### Problem
- Exception is dropped after upgrade of Sphinx from version 1.6.5 to 1.7.5

#### Procedure to reproduce the problem
```
git clone --recursive https://github.com/espressif/esp-adf.git
cd esp-adf/docs
sudo apt-get install doxygen
pip install -r requirements.txt
pip install sphinx==1.7.5
cd en
make html
```

#### Error logs / results
```
writing output... [  3%] api-guides/build-system                                                                 
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 3543, in matches
    if s.identOrOp != identOrOp:
AttributeError: 'Symbol' object has no attribute 'identOrOp'
The full traceback has been saved in /tmp/sphinx-err-xau27x.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2
```

#### Expected results
Compilation should complete without any exceptions

### Reproducible project / your project
- https://github.com/espressif/esp-adf/tree/master/docs/en

### Environment info
- OS: Ubuntu 16.04 LTS
- Python version: 2.7.12
- Sphinx version: 1.7.5
- Breathe 4.9.0

Ref. https://github.com/michaeljones/breathe/issues/282#issuecomment-394151316

**Comment by jakobandersen** [comment]
I can't reproduce the bug. Can you provide the full stacktrace? Try completely removing old compiled files, it may be some pickled old data structures that causes the problem.

**Comment by krzychb** [comment]
@jakobandersen you are right. The issue is gone after completely removing old compiled files. I am really sorry for a false alarm.

**Comment by jakobandersen** [comment]
No problem, thanks for checking.
