### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_SETTINGS'

### ISSUE THREAD

**Issue by stevepiercy** [sphinx-doc/sphinx#5433]
Subject: ImportError: cannot import name 'DEFAULT_SETTINGS'

### Problem

With the release of Sphinx 1.8.0, our builds have started to fail with the error message `ImportError: cannot import name 'DEFAULT_SETTINGS'`.

#### Error logs / results

See:
https://travis-ci.org/Pylons/pyramid/jobs/428634951#L497

See also https://github.com/Pylons/pyramid/issues/3350 and https://github.com/sphinx-doc/sphinx/issues/109

**Comment by cdunklau** [comment]
This is quite easy to reproduce on my Mac, running Python 3.5.3 from pyenv. There's an import cycle `sphinx.writers.latex` -> `sphinx.builders.latex` -> `sphinx.writers.latex` 

Setup:

```
--> $ python3 -m venv sphinxenv

--> $ sphinxenv/bin/pip install --upgrade pip setuptools wheel
<snip>
Successfully installed pip-18.0 setuptools-40.2.0 wheel-0.31.1

--> $ sphinxenv/bin/pip install sphinx==1.8.0
<snip>
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.11 babel-2.6.0 certifi-2018.8.24 chardet-3.0.4 docutils-0.14 idna-2.7 imagesize-1.1.0 packaging-17.1 pyparsing-2.2.0 pytz-2018.5 requests-2.19.1 six-1.11.0 snowballstemmer-1.2.1 sphinx-1.8.0 sphinxcontrib-websupport-1.1.0 urllib3-1.23
```

Reproduction is just to import the same thing referenced in the Travis build:

```
--> $ sphinxenv/bin/python
Python 3.5.3 (default, Apr 11 2017, 21:55:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sphinx.writers.latex import LaTeXTranslator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cdunklau/test/sphinxenv/lib/python3.5/site-packages/sphinx/writers/latex.py", line 27, in <module>
    from sphinx.builders.latex.nodes import captioned_literal_block, footnotetext
  File "/Users/cdunklau/test/sphinxenv/lib/python3.5/site-packages/sphinx/builders/latex/__init__.py", line 37, in <module>
    from sphinx.writers.latex import DEFAULT_SETTINGS, LaTeXWriter, LaTeXTranslator
ImportError: cannot import name 'DEFAULT_SETTINGS'
>>> import sphinx  
>>> sphinx.version_info
(1, 8, 0, 'final', 0)
```

**Comment by cdunklau** [comment]
Here's my bisect log... my first ever git bisect, but I'm fairly sure I did it right. I'm adding it here with the hope that it will be helpful in isolating the problem.

```
git bisect start
# bad: [16533cff9a1e20fc10ec78eaf7c4796cd3552965] Bump to 1.8.0 final
git bisect bad 16533cff9a1e20fc10ec78eaf7c4796cd3552965
# good: [1cd87a11ef8df6b783d2e48d9668370a4e1640c9] Bump to 1.7.9 final
git bisect good 1cd87a11ef8df6b783d2e48d9668370a4e1640c9
# bad: [a4c7be6fcdf6d6fcef8d781707a86a7eb8216bb5] Move MathDomain to sphinx.domains.math
git bisect bad a4c7be6fcdf6d6fcef8d781707a86a7eb8216bb5
# good: [f26db5b2287b3c4fc12ce5649507440c6f2dc456] Merge pull request #4742 from tk0miya/refactor_enumerable_nodes
git bisect good f26db5b2287b3c4fc12ce5649507440c6f2dc456
# good: [fbe7531685de0e7fe3bf0f19f576b4a58844dcc5] Merge pull request #4910 from tk0miya/deprecate_values_for_html_search_options
git bisect good fbe7531685de0e7fe3bf0f19f576b4a58844dcc5
# bad: [8febb093736052162f8d41e0b136ab692f375d27] Merge branch 'master' into refactor_latex_footnotes
git bisect bad 8febb093736052162f8d41e0b136ab692f375d27
# good: [7a8d1dc08c94c96e29da235b065a2eba6b056cc5] doc: Fix line length
git bisect good 7a8d1dc08c94c96e29da235b065a2eba6b056cc5
# good: [d8f4e47fc8c0a6358c3451e1147d21aaca82cceb] Fix broken testcase caused by path separator
git bisect good d8f4e47fc8c0a6358c3451e1147d21aaca82cceb
# good: [cbf4ee24f9c7f83a7558786d2f43c9b79ad60418] Fix #4811: The files under html_static_path are excluded from source
git bisect good cbf4ee24f9c7f83a7558786d2f43c9b79ad60418
# bad: [89d68d9ac335c2530defc003cd7e54031228db80] refactor: Add LaTeXFootnoteTransform to restructure footnotes for LaTeX
git bisect bad 89d68d9ac335c2530defc003cd7e54031228db80
# bad: [1c65ff762e9e746bdbbcf44549791adde347a71a] Apply ShowUrlsTransform at LaTeXBuilder
git bisect bad 1c65ff762e9e746bdbbcf44549791adde347a71a
# bad: [a062142701042bc04c75cc5a5dfecbbe03cc1f04] refactor: ShowUrlsTransform
git bisect bad a062142701042bc04c75cc5a5dfecbbe03cc1f04
# first bad commit: [a062142701042bc04c75cc5a5dfecbbe03cc1f04] refactor: ShowUrlsTransform
```

**Comment by cdunklau** [comment]
A workaround would be to `import sphinx.builders.latex.nodes` first. This avoids the circular import:

```
--> $ venv/bin/python
Python 3.5.3 (default, Apr 11 2017, 21:55:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Enabled tab completion
>>> import sphinx.builders.latex.nodes
>>> from sphinx.writers.latex import LaTeXTranslator
>>> sphinx.version_info
(1, 8, 0, 'final', 0)
```

**Comment by tk0miya** [comment]
Fixed by #5445 
Thank you for reporting.
