### ISSUE TITLE
AttributeError: partially initialized module 'sphinx.addnodes' has no attribute 'versionmodified'

### ISSUE THREAD

**Issue by jschueller** [sphinx-doc/sphinx#8016]
since a few weeks I've got this error from latest git version:
```
$ python -c "import  sphinx.directives"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/devel/.local/lib/python3.8/site-packages/sphinx/directives/__init__.py", line 19, in <module>
    from sphinx import addnodes
  File "/home/devel/.local/lib/python3.8/site-packages/sphinx/addnodes.py", line 18, in <module>
    from sphinx.util import docutils
  File "/home/devel/.local/lib/python3.8/site-packages/sphinx/util/__init__.py", line 46, in <module>
    from sphinx.util.nodes import (   # noqa
  File "/home/devel/.local/lib/python3.8/site-packages/sphinx/util/nodes.py", line 187, in <module>
    addnodes.versionmodified,
AttributeError: partially initialized module 'sphinx.addnodes' has no attribute 'versionmodified' (most likely due to a circular import)
```

It seems to come from fb7b0ee5718af07c8eddf49f71742f6b97f7fd65:
```
$ git clone https://github.com/sphinx-doc/sphinx.git && cd sphinx && git bisect start 2cf3e7cae2a7677bc3b2b87456a9129f426d27e1 68abe09afe9f33a3ce0ea4e909a78377b2069ddf && echo -e "#!/bin/sh\npython setup.py install --user\npython -c 'import sphinx.directives'" > /tmp/brun.sh && chmod a+rx /tmp/brun.sh && cat /tmp/brun.sh && $ git bisect run /tmp/brun.sh
...
fb7b0ee5718af07c8eddf49f71742f6b97f7fd65 is the first bad commit
commit fb7b0ee5718af07c8eddf49f71742f6b97f7fd65
Author: Takeshi KOMIYA <i.tkomiya@gmail.com>
Date:   Tue May 5 22:12:52 2020 +0900

    Fix #7619: Duplicated node IDs are generated if node has multiple IDs
```

cc @tk0miya
