### PR TITLE
Fix #4885: jsdomain also crashed with duplicated objects

### LINKED ISSUE #4885: Django docs crash with `AttributeError: 'DirectiveAdapter' object has no attribute 'env'``
After upgrading from Sphinx 1.7.2 to 1.7.3, building [Django's docs](https://github.com/django/django/) fails with:
```
Exception occurred:
  File "/home/jenkins/workspace/docs/tests/.env/lib/python3.4/site-packages/sphinx/domains/python.py", line 568, in run
    (modname, self.env.doc2path(modules[modname])),
AttributeError: 'DirectiveAdapter' object has no attribute 'env'`
```
Bisected to f4f693eff7b081785cc5704a6ff22cf0371355f3.

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #4885.
- javascript domain also crashes with duplicated objects

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

### CODE REVIEW

**Comment by knorth55** [comment]
I have not familiar with `sphinx-js` code, but should it be`modules[mod_name]` -> `modules[mod_name][0]` as  #4887 ?
If I'm wrong, I'm so sorry.

**Comment by tk0miya** [comment]
Thank you for reviewing!

In python domain, the `modules[mod_name]` has four membered tuple as a value:
https://github.com/sphinx-doc/sphinx/blob/5909ccff0282c0a320f5533cab40f2eff749fd31/sphinx/domains/python.py#L589-L592

On the other hand, in javascript domain (this case), the `modules[mod_name]` has single string as a value:
https://github.com/sphinx-doc/sphinx/blob/5909ccff0282c0a320f5533cab40f2eff749fd31/sphinx/domains/javascript.py#L267

So it `[0]` index is not needed here.

**Comment by knorth55** [comment]
Oh, that's right! Thank you!
