### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'domains'

### ISSUE THREAD

**Issue by imcom** [sphinx-doc/sphinx#3804]
Subject: AttributeError: 'Sphinx' object has no attribute 'domains'
### Problem
Doc failed to build using Sphinx v1.6.1 and sphinxcontrib-httpdomain==1.5.0

#### Procedure to reproduce the problem
```
tox
```

#### Error logs / results
```
Exception occurred:
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinxcontrib/autohttp/flask.py", line 46, in setup
    if 'http' not in app.domains:
AttributeError: 'Sphinx' object has no attribute 'domains'
The full traceback has been saved in /var/folders/7y/d0gvp5pd40ndkwhqcg6qqwnm0000gq/T/sphinx-err-NKU3op.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError: '/Users/ij0151/GitHub/yabgp/.tox/docs/bin/sphinx-build -W -b html doc/source doc/build'
```

#### Expected results
Doc should build successfully 

### Reproducible project / your project
https://github.com/imcom/yabgp

### Environment info
- OS: Mac 10.12.4
# Sphinx version: 1.6.1
# Python version: 2.7.11 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 195, in __init__
    self.setup_extension(extension)
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 455, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/Users/ij0151/GitHub/yabgp/.tox/docs/lib/python2.7/site-packages/sphinxcontrib/autohttp/flask.py", line 46, in setup
    if 'http' not in app.domains:
AttributeError: 'Sphinx' object has no attribute 'domains'

**Comment by tk0miya** [comment]
Same as #3760.
Thanks,
