### ISSUE TITLE
HTML search not working

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#467]
Search doesn't currently work on either 1.0b2 or 1.0b2+/7473a3e2e009  Firebug complains with 

```
#!javascript

Search.loadIndex is not a function
file:///Users/hobu/svn/msdocs.56/build/html/en/search.html?q=mapfile&check_keywords=yes&area=default
Line 31
```

loadIndex doesn't seem to exist anymore.  

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/467
- Originally reported by: Howard Butler
- Originally created at: 2010-07-12T17:30:51.996

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-07-19 08:57:25+00:00_

Search.loadIndex does exist in searchtools.js -- can you check you have the correct version?

**Comment by shimizukawa** [comment]
_From Anonymous on 2010-07-19 21:23:58+00:00_

I have the same problem with 1.0b2, both locally, and on the server that Howard refers to (http://www.mapserver.org/).  On both machines the /_static/searchtools.js file does not contain the loadIndex function.

But then I asked myself "where does this /_static/searchtools.js file come from?".  So on my local machine I found several versions of this file in my C:/Python26/ folder:

{{{
C:\Python26\Lib\site-packages\Sphinx-1.0b2-py2.6.egg\sphinx\themes\basic\searchtools.js
C:\Python26\Lib\site-packages\Sphinx-0.6.5-py2.6.egg\sphinx\themes\basic\searchtools.js
C:\Python26\Lib\site-packages\Sphinx-0.6.3-py2.6.egg\sphinx\themes\basic\searchtools.js
}}}

Our 1.0b2 copies contain the function, but our older ones do not.

I believe this means that mapserver.org uses a theme from pre-sphinx-1.0, and that we'll have to upgrade.  Am I correct?

**Comment by shimizukawa** [comment]
_From Jeff McKenna on 2010-07-19 21:24:55+00:00_

sorry that last comment was from me.  -jeff

**Comment by shimizukawa** [comment]
_From Jeff McKenna on 2010-07-22 18:17:53+00:00_

As discussed on the sphinx-dev list (http://groups.google.com/group/sphinx-dev/browse_thread/thread/a670601aa72887a9) this problem was due to old 0.6.5 theme files (searchtools.js, doctools.js, etc.).  Removing them and then rebuilding solves the problem.
