### ISSUE TITLE
Missing references raising exception

### ISSUE THREAD

**Issue by hamishwillee** [sphinx-doc/sphinx#2429]
Rather than getting a warning when an item linked by a reference does not exist, I'm getting exceptions. Everything works fine if I link to an existing anchor. So for example, a single document with link as shown:

```
:ref:`NOT_EXISTS`
```

Will cause

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1548, in _warn_missing_reference
    self.warn_node(msg % {'target': target}, node, type='ref', subtype=typ)
TypeError: _warn_node() got an unexpected keyword argument 'type'
```

The function takes a kwarg*\* so I'm at a lost how this error could occur: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/environment.py#L1548

The full bug output listed below:

```
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   done
#   writing output... [  0%] docs/3dr-kits-and-best-practices
#   writing output... [  0%] docs/ac2_followme
#   writing output... [  1%] docs/ac2_guidedmode
#   writing output... [  1%] docs/ac2_positionmode
#   writing output... [  2%] docs/ac2_simple_geofence
#   writing output... [  2%] docs/ac_rollpitchtuning
#   writing output... [  3%] docs/ac_throttlemid
#   writing output... [  3%] docs/ac_tipsfornewpilots
#   writing output... [  3%] docs/acro-mode
# Loaded extensions:
#   sphinx.ext.autodoc (1.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/intersphinx.pyc
#   sphinxcontrib.youtube (unknown version) from /usr/local/lib/python2.7/dist-packages/sphinxcontrib_youtube-1.0dev_20160323-py2.7.egg/sphinxcontrib/youtube.pyc
#   alabaster (0.7.7) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinx.ext.pngmath (1.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/pngmath.pyc
#   sphinx.ext.todo (1.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/todo.pyc
#   sphinx.ext.ifconfig (1.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main

    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1512, in resolve_references
    self._warn_missing_reference(refdoc, typ, target, node, domain)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1548, in _warn_missing_reference
    self.warn_node(msg % {'target': target}, node, type='ref', subtype=typ)
TypeError: _warn_node() got an unexpected keyword argument 'type'
```

**Comment by hamishwillee** [comment]
Works fine on Sphinx 1.3 but not later. Sphinx installed using the Sphinx RTD Theme on Ubuntu 14.02

**Comment by jputrino** [comment]
I got the same error; full traceback below. Sphinx installed using the Sphinx RTD theme on Mac OSX. I also confirmed that it works fine in1.3.

```
# Sphinx version: 1.4
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 23%] includes/ref_features
#   writing output... [ 30%] includes/ref_restrictions
#   writing output... [ 38%] includes/topic_before-you-begin
#   writing output... [ 46%] includes/topic_configure-neutron-lbaasv2
#   writing output... [ 53%] includes/topic_configure-the-agent
#   writing output... [ 61%] includes/topic_install-f5-lbaasv2-packages
#   writing output... [ 69%] includes/topic_tip-stop-agent
#   writing output... [ 76%] includes/topic_troubleshooting-f5agent
#   writing output... [ 84%] includes/topic_troubleshooting-general
#   writing output... [ 92%] index
# Loaded extensions:
#   sphinx.ext.autodoc (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.7) from /Library/Python/2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.viewcode (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.coverage (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.todo (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.ifconfig (1.4) from /Library/Python/2.7/site-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Library/Python/2.7/site-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/Library/Python/2.7/site-packages/sphinx/environment.py", line 1512, in resolve_references
    self._warn_missing_reference(refdoc, typ, target, node, domain)
  File "/Library/Python/2.7/site-packages/sphinx/environment.py", line 1548, in _warn_missing_reference
    self.warn_node(msg % {'target': target}, node, type='ref', subtype=typ)
TypeError: _warn_node() got an unexpected keyword argument 'type'
/var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-1IthE_.log (END)
```

**Comment by hamishwillee** [comment]
@jputrino I hope "they" fix this. In the meantime we reverted to Sphinx 1.3. Just FYI, in this version our the template field {{suffix}} did not work.

**Comment by tk0miya** [comment]
I'll take a look

**Comment by tk0miya** [comment]
Sorry, I can't reproduce the problem.
Could you give me minimal document?

**Comment by jputrino** [comment]
@tk0miya - do you want to try forking my repo? The one that's throwing errors for me is https://github.com/jputrino/f5-openstack-lbaasv2, -b is feature.docs-refactor. I got the error on 1.3.5 and 1.4, I believe.

**Comment by tk0miya** [comment]
@jputrino It looks `Sphinx.environment.warn_node` is customized on your conf.py.

```
# Ignore external image warnings

import sphinx.environment
from docutils.utils import get_source_line

def _warn_node(self, msg, node):
    if not msg.startswith('nonlocal image URI found:'):
        self._warnfunc(msg, '%s:%s' % get_source_line(node))

sphinx.environment.BuildEnvironment.warn_node = _warn_node
```

The interface of the internal function is changed on Sphinx-1.4.
You have to rewrite the code to accept keyword arguments (like `**kwargs`).

BTW, could you open a new issue to ignore the warning?
Now we are ready to do that if you want.

**Comment by jputrino** [comment]
@tk0miya - Thanks! Just to clarify -- do you want me to open a new issue (feature request) for ignoring the external image warnings?

**Comment by tk0miya** [comment]
Yes, please.
I will add the option to ignore them in feature version.

**Comment by tk0miya** [comment]
@hamishwillee How about your case?
Please check whether your conf.py overrides `Sphinx.environment.warn_node` or not.
If not, could you share your project or make minimal project to reproduce the problem?

Thanks,

**Comment by hamishwillee** [comment]
@tk0miya @jputrino THanks. My case is identical. Which proves that "random code from the internet really isn't always better than your own thoughtout code :-0". 

Agree with Jodie that it would be good to be able to selectively hide those warnings on non-local images.

**Comment by hamishwillee** [comment]
PS Yes, this can be closed!

**Comment by tk0miya** [comment]
Ok, I close this now.
Thank you for reporting!

**Comment by hamishwillee** [comment]
Thanks. FYI only, I added a link to this error from the source of the problem code: http://stackoverflow.com/questions/12772927/specifying-an-online-image-in-sphinx-restructuredtext-format

**Comment by jquast** [comment]
As the author of the random code on the internet in question, I apologize!

(Unfortunately I posted using an anonymous account on stack overflow, I cannot revise or fix this answer.)

**Comment by hamishwillee** [comment]
@jquast I read a sarcastic post somewhere that: "code you find somewhere on the internet is always better than well crafted code you create yourself". In other words "buyer beware". Your code snippet certainly saved me a bit of time.
