### ISSUE TITLE
Building docs using `ext.napoleon` fails on python >= 3.10

### ISSUE THREAD

**Issue by PaarthShah** [sphinx-doc/sphinx#11698]
### Describe the bug

I'm a maintainer of https://github.com/poljar/matrix-nio. We use the `"sphinx.ext.napoleon"` extension.

Currently, the build fails due to:
```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/matrix-nio/envs/doc-fix/lib/python3.11/site-packages/sphinx/ext/napoleon/docstring.py", line 123, in __init__
    elif isinstance(obj, collections.Callable):  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
The full traceback has been saved in /tmp/sphinx-err-chutem4_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This doesn't appear to be an isolated issue: https://github.com/Trusted-AI/AIF360/issues/496

### How to Reproduce

Minimal method:
in `conf.py`:
```
extensions = [
    "sphinx.ext.napoleon",
]
```
And build using `python3.11`

### Environment Information

```text
Platform:              linux; (Linux-6.5.5-arch1-1-x86_64-with-glibc2.38)
Python version:        3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

```python
["sphinx.ext.napoleon"]
```

### Additional context

readthedocs

**Comment by PaarthShah** [comment]
Nevermind: turns out it was due to a low `sphinx` version on readthedocs.
