### ISSUE TITLE
ImportError: cannot import name 'LaTeXWriter'

### ISSUE THREAD

**Issue by stevepiercy** [sphinx-doc/sphinx#4889]
### Problem
Between Sphinx 1.7.2 and 1.7.3, the latex builders were moved into a package. Now some of the writers are not importable.

See also https://github.com/Pylons/pyramid/pull/3261

#### Procedure to reproduce the problem
We use Travis-CI and tox to build docs on Python 3.5. [See Travis-CI log for Pyramid](https://travis-ci.org/Pylons/pyramid/jobs/369993136#L543-L561)

#### Error logs / results
```docs runtests: commands[1] | make -C docs doctest html epub BUILDDIR=/home/travis/build/Pylons/pyramid/.tox/docs SPHINXOPTS=-W -E
make: Entering directory `/home/travis/build/Pylons/pyramid/docs'
sphinx-build -b doctest -d /home/travis/build/Pylons/pyramid/.tox/docs/doctrees  -W -E . /home/travis/build/Pylons/pyramid/.tox/docs/doctest
Running Sphinx v1.7.3
Configuration error:
There is a programable error in your configuration file:
Traceback (most recent call last):
  File "/home/travis/build/Pylons/pyramid/.tox/docs/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/travis/build/Pylons/pyramid/.tox/docs/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 27, in <module>
    from sphinx.writers.latex import LaTeXTranslator
  File "/home/travis/build/Pylons/pyramid/.tox/docs/lib/python3.5/site-packages/sphinx/writers/latex.py", line 26, in <module>
    from sphinx.builders.latex.transforms import URI_SCHEMES, ShowUrlsTransform  # NOQA  # for compatibility
  File "/home/travis/build/Pylons/pyramid/.tox/docs/lib/python3.5/site-packages/sphinx/builders/latex/__init__.py", line 35, in <module>
    from sphinx.writers.latex import LaTeXWriter, LaTeXTranslator
ImportError: cannot import name 'LaTeXWriter'
make: *** [doctest] Error 2
make: Leaving directory `/home/travis/build/Pylons/pyramid/docs'
ERROR: InvocationError for command '/usr/bin/make -C docs doctest html epub BUILDDIR=/home/travis/build/Pylons/pyramid/.tox/docs SPHINXOPTS=-W -E' (exited with code 2)
```

- https://travis-ci.org/Pylons/pyramid/jobs/369993136#L543-L561

#### Expected results
Docs should pass the build in [Travis-CI like in Sphinx 1.7.2](https://travis-ci.org/Pylons/pyramid/jobs/365457209#L544)

### Reproducible project / your project
- https://github.com/pylons/pyramid

### Environment info
- macOS and Ubuntu 14.04.5 LTS
- Python version: 3.5
- Sphinx version: 1.7.3 (worked fine in 1.7.2)
- tox

**Comment by tk0miya** [comment]
OMG! `sphinx.writers.latex` causes recursive import if it is imported before `sphinx.builders.latex`!
```
  File "conf.py", line 27, in <module>
    from sphinx.writers.latex import LaTeXTranslator
```
