### ISSUE TITLE
autosummary breaks doctest and use of type annotations

### ISSUE THREAD

**Issue by lukasturcani** [sphinx-doc/sphinx#11681]
### Describe the bug

using an autosummary command in the documentation, causes doctest blocks to read the 
`__annotations__` attribute incorrectly. Specifically, the `__annotations__` will show type hints 
from parent classes. the same is true if `inspect.get_annotations()` is used.

Weirdly -- if the `make -C docs doctest` command is run twice -- the issue goes away. There may
be some kind of caching issue. Only the first time when the sources are being read does this
issue appear.

### How to Reproduce

I have made a repository https://github.com/lukasturcani/debug_annotations -- the README documents the bug
and how to reproduce it

### Environment Information

```text
i used python 3.11 and the latest version of sphinx
```

### Sphinx extensions

```python
["sphinx.ext.doctest", "sphinx.ext.autosummary"]
```

**Comment by picnixz** [comment]
- Did it appear in Sphinx prior to 7.2.x?
- Can you bisect the bad commit?

**Comment by lukasturcani** [comment]
I tested on Python 3.9 -- because the versions which need testing fail for versions greater than this.

I did bisect and was left with these commits:

```
1f860cb77ee3183c3b2c96058c4992f4f5870c52
d006c66e237f1a5bc4e95b25a5176fa8dc9de65a
77da494173715c76ffd3158b368392c196607fbb
afa80dfe03c22e4278ea57648c4db4640fdc36e8
0aea6d318c0432340c9be59853ce5ba196907a10
abbd0056127e0834fff8933c25637fe2179b2332
260e26cad4fb2753653c07d639118bc899e8f68d
bf2e69ad131b2a1b59d47dd8cd368942c61e0cf6
104d0a3f6914f7ba9031fe396bd99ad29990104d
43434a086cc1967bf15197ca4c59efd63dec2d4a
531a5ae9ef855761407d44fb49064ae6227868f5
f12f5bc0757e5a3f3029fee8c23b2339ac0cc738
00bc3465b3a7a68b7e59cb9cccfb2a91c3afced7
35dda449c05833c14b849a8270a523e5817e2bb2
6f8d9390df41d377621020767b00e35601474871
930bf6c327b31aec6112359695f35a2c77fbae21
d82c8a78900e48c037827d3c522acecd5a0b530c
829de019c5c5ee08a8f99912bf6a7e4ed67d83e7
```

The reason that there are multiple commits is that some commits threw and unrelated error, namely

```
Traceback (most recent call last):
  File "/home/lukas/projects/debug-annotations/.venv/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx', 'console_scripts', 'sphinx-build')())
  File "/home/lukas/projects/debug-annotations/.venv/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/lukas/projects/debug-annotations/.venv/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/lukas/projects/debug-annotations/.venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lukas/projects/sphinx/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/lukas/projects/sphinx/sphinx/application.py", line 41, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/lukas/projects/sphinx/sphinx/registry.py", line 26, in <module>
    from sphinx.builders import Builder
  File "/home/lukas/projects/sphinx/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/home/lukas/projects/sphinx/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/lukas/projects/debug-annotations/.venv/lib/python3.9/site-packages/jinja2/__init__.py)
make: *** [Makefile:20: doctest] Error 1
make: Leaving directory '/home/lukas/projects/debug-annotations/docs'
```

so i had to `bisect skip` them

**Comment by picnixz** [comment]
Wait, so why does it work for me on 4.x + 3.11???

I know that there was some changes in `__annotations__` but I don't remember whether it was introduced after 3.9 or not. 

I only tested the code on my phone so I might have messed up. I'll be able to check it on my computer next week or the week after.

**Comment by lukasturcani** [comment]
there are some versions of `4.x` which do work on 3.11 but some of the ealier ones do not because of this issue "https://github.com/sphinx-doc/sphinx/issues/9512" (i think that issue i closed my terminal so i've lost the exact error messege but think it was this one)

**Comment by picnixz** [comment]
I investigated a bit using verbose output (`-vvv`), and I think I know the issue. The second run does not re-read sources so there are some events that are not fired and it's likely that one of these events is the one responsible for updating the `__annotations__` attribute.

You can see this as follows:

* First run: `reading sources... [100%] index`
* Second run: `reading sources...`

When reading `index`, you'll see that there are `AttributeError` being raised (`-vvv` flags are needed) but the second run does not have this issue. As for how to correct this, I don't know for now, so any PR is welcomed.

**Comment by AA-Turner** [comment]
Thanks to everyone who was working on this issue during the EuroPython sprints!

A

**Comment by AA-Turner** [comment]
May have been fixed by #13935.

A

**Comment by AA-Turner** [comment]
Confirmed, reproducer no longer fails.

A
