### ISSUE TITLE
error compiling django doc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#803]
error message:

```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  7&#37;] howto/custom-management-commands
Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinx/writers/html.py", line 120, in visit_desc_parameter
    self.body.append(self.param_separator)
AttributeError: DjangoHTMLTranslator instance has no attribute 'param_separator'
The full traceback has been saved in /tmp/sphinx-err-4VlUDu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

my fix in file .../writers/html.py

```
118     def visit_desc_parameter(self, node):
119         if not self.first_param:
120             self.body.append(",")#self.param_separator)
121         else:
122             self.first_param = 0
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/803
- Originally reported by: Anonymous
- Originally created at: 2011-10-21T16:18:02.578

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-11-01 08:12:20+00:00_

It seems that the Django HTML translator needs to be updated to work with Sphinx 1.1.

**Comment by shimizukawa** [comment]
_From Jakub Wilk on 2011-11-01 18:18:15+00:00_

Just for the record, this has been fixed in Django VCS:
https://code.djangoproject.com/changeset/16231
