### ISSUE TITLE
Updating sphinx from 1.8.0 to 1.8.1 results in warning

### ISSUE THREAD

**Issue by topic2k** [sphinx-doc/sphinx#6047]
Previously posted in forum: https://groups.google.com/d/msg/sphinx-users/C1JJH62UMaM/AigXvOC-CQAJ

**Describe the bug**
After the updating sphinx from 1.8.0 to 1.8.1 building of the docs print these warnings:

```shell
WARNING: error while formatting arguments for eg.TriggerEvent: 'function' object has no attribute '__bases__'
WARNING: error while formatting arguments for eg.PrintError: 'function' object has no attribute '__bases__'
```

**To Reproduce**
Steps to reproduce the behavior (Windows only):
```
$ git clone https://github.com/EventGhost/EventGhost
$ cd EventGhost\_build\data
$ sphinx-build -b html docs tmp
```

**Expected behavior**
A sphinx build run without errors.

**Your project**
https://github.com/EventGhost/EventGhost
https://github.com/EventGhost/EventGhost/tree/master/_build/data/docs

**Environment info**
- OS: Windows
- Python version: 2.7.15
- Sphinx version: 1.8.1
- Sphinx extensions: sphinx.ext.autodoc

**Additional context**

> [Komiya Takeshi wrote](https://groups.google.com/d/msg/sphinx-users/C1JJH62UMaM/GmpgG9otFwAJ)
>I think that might be related with this change.
https://github.com/sphinx-doc/sphinx/compare/sphinx-doc:16533cf...sphinx-doc:65a560f#diff-48ca4d6544b092f35d729127500bff5fR1058

**Comment by tk0miya** [comment]
As I commented in the group, what I'd like to know is how `eg.TriggerEvent` and `eg.PrintError` are implemented. It is strongly related with this problem. In your post, replacing `isfunction()` by `isroutine()` is needed for your code. It means these code are not functions.

Could you let me know how to implement them? Unfortunately, I don't have windows PC. so it would be very nice if you let me know the location of code.

**Comment by topic2k** [comment]
`eg.TriggerEvent` is implemented in [eg.Classes.EventThread.py](https://github.com/EventGhost/EventGhost/blob/d6b167f30e3dd420d130b715b554a7ce886e42b7/eg/Classes/EventThread.py#L105).
`eg.PrintError` is implemented in [eg.Classes.Log.py](https://github.com/EventGhost/EventGhost/blob/d6b167f30e3dd420d130b715b554a7ce886e42b7/eg/Classes/Log.py#L206)

**Comment by tk0miya** [comment]
It seems both are not functions. They're methods. `inspect.isfunction()` returns False value for methods.
```
$ python
Python 3.7.1 (default, Oct 23 2018, 19:06:59)
[Clang 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo:
...     def meth(self): pass
...
>>> import inspect
>>> inspect.isfunction(Foo().meth)
False
```

I feel very strange to use `function` directive for methods...

**Comment by topic2k** [comment]
With that information i stepped through the building and the source files. When i replace `.. autofunction:: eg.TriggerEvent` in [eg/index.rst](https://github.com/EventGhost/EventGhost/blob/master/_build/data/docs/eg/index.rst#L55) with `.. automethod:: eg.EventThread.TriggerEvent` the build generates no warning (for TriggerEvent), but in the output we then have EventThread.TriggerEvent instead of eg.TriggerEvent.
Can it be because we [assign the method](https://github.com/EventGhost/EventGhost/blob/d6b167f30e3dd420d130b715b554a7ce886e42b7/eg/Core.py#L362) to the [dynamic module](https://github.com/EventGhost/EventGhost/blob/d6b167f30e3dd420d130b715b554a7ce886e42b7/eg/__init__.py#L39)?

If this is special case with our source code, is there way i can automatically replace EventThread.TriggerEvent with eg.TriggerEvent in the generated file?

**Comment by topic2k** [comment]
I've made a small runable app that also runs on Linux. Run `python2 build_docs.py` to see the warning. (python3 doesn't raise the warning)

[EventGhost.zip](https://github.com/sphinx-doc/sphinx/files/2852517/EventGhost.zip)

**Comment by tk0miya** [comment]
I just posted PR #6083. I suppose this fixes the warning. Could you try it please?

**Comment by topic2k** [comment]
The fix results in a correct build. Thank you.

**Comment by tk0miya** [comment]
Thank you for confirmation :-)
