### ISSUE TITLE
object has no attribute '__qualname__' after v3.1.0

### ISSUE THREAD

**Issue by dbaio** [sphinx-doc/sphinx#7856]
**Describe the bug**
After updating Sphinx to 3.1.0 and 3.1.1, getting this error: `object has no attribute '__qualname__'`

**To Reproduce**
```
$ git clone https://github.com/weilbith/notmuch-python-bindings.git
$ cd notmuch-python-bindings/docs
$ cd docs
$ make html
[...]
Running Sphinx v3.1.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.python.org/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='docs.python.org', port=443): Max retries exceeded with url: /objects.inv (Caused by NewConnectionError("<urllib3.connection.VerifiedHTTPSConnection object at 0x80481c450>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [  8%] database
reading sources... [ 16%] filesystem
reading sources... [ 25%] index
reading sources... [ 33%] message
reading sources... [ 41%] messages
reading sources... [ 50%] notes
reading sources... [ 58%] query
reading sources... [ 66%] quickstart
reading sources... [ 75%] status_and_errors

Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1404, in format_signature
    qualname = '.'.join([self._signature_class.__qualname__,
AttributeError: 'Status' object has no attribute '__qualname__'
The full traceback has been saved in /tmp/sphinx-err-vxd7puu8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
*** Error code 2
```

**Expected behavior**
On earlier versions, `make html` works fine.

**Your project**
https://github.com/weilbith/notmuch-python-bindings/tree/master/docs

**Environment info**
- OS: Mac/FreeBSD
- Python version: 3.7
- Sphinx version: 3.1.0 / 3.1.1
- Sphinx extensions:  ['sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo']
- Extra tools: 

**Additional context**
https://github.com/weilbith/notmuch-python-bindings/issues/2

**Comment by tk0miya** [comment]
It seems `notmuch.STATUS` is an enum object, not a class. So I don't think this is not a bug of autodoc.
https://github.com/weilbith/notmuch-python-bindings/blob/0867e4166002e3584c442a0646b0d67fe9dd6e04/notmuch/errors.py#L48-L62

Note: You can deceive autodoc via adding `__qualname__` to `STATUS` object same as what you do to `__name__`.

**Comment by tk0miya** [comment]
I posted a PR #7858  to prevent a crash even if an invalid object is passed.

**Comment by dbaio** [comment]
> I posted a PR #7858 to prevent a crash even if an invalid object is passed.

Thank you for taking a look.
It will help and I reported this issue to the project as well.
