### ISSUE TITLE
Sphinx 3.5 causes `AttributeError: 'tuple' object has no attribute 'sort'` on `ctx['css_files']`

### ISSUE THREAD

**Issue by webknjaz** [sphinx-doc/sphinx#8889]
**Describe the bug**

Sphinx 3.5 broke the "any iterable" expectation for `css_files` in HTML context: by calling `.sort()` on it, the expectation became "list-only",  not "any iterable".
And now when there's a tuple in `css_files`, it breaks with an `AttributeError`:
```python-traceback
  File "/home/runner/work/pylibssh/pylibssh/.tox/build-docs/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1039, in handle_page
    ctx['css_files'].sort(key=lambda js: js.priority)
AttributeError: 'tuple' object has no attribute 'sort'
```

**To Reproduce**

Add `html_context = {'css_files': ()}` to `conf.py` and build with `html` or `dirhtml` builder.

**Expected behavior**

Same as before 3.5: no error.

**Your project**

https://github.com/ansible/pylibssh

**Screenshots**

N/A

**Environment info**

- OS: N/A
- Python version: N/A
- Sphinx version: 3.5.0
- Sphinx extensions: `sphinx_ansible_theme`
- Extra tools: N/A

**Additional context**

- https://github.com/ansible/pylibssh/pull/174
- https://readthedocs.org/projects/ansible-pylibssh/builds/13017980/

**Comment by tk0miya** [comment]
>To Reproduce
>Add html_context{'css_files': ()} to conf.py and build with html or dirhtml builder.

Sorry. I don't understand what are you going. Do you want to disable all the CSS files on the HTML output? I think #8893 will also avoid the crash when you set tuple to `html_context['css_files']`. And it seems your project already switched to the list. But I can't say it will work in the future Sphinx (Since 4.0, some CSS will be moved into css_files).

**Comment by webknjaz** [comment]
I think it was originally set to an empty tuple to reset some theme defaults. And this approach can be found in other places. Like https://github.com/ansible/ansible/blob/00bd0b8/docs/docsite/rst/conf.py#L154-L155.

I only reported this because it looks like this side-effect was unplanned. But if Sphinx wants to enforce lists, it's fine — we just need this to be documented somewhere (and maybe go through the deprecation warnings procedure).

**Comment by tk0miya** [comment]
Indeed, this is unexpected behavior. I don't know who overrides css_files and script_files via `html_context`. So this must be a bug. So it should be fixed (like #8893 does).

My concern is why do you make it empty (not replacing new one). Since 4.0, some additional style files will be added into `css_files`. But this hack resets them forcedly. As a result, styles will be disabled on upgrading to the next major release.
https://github.com/sphinx-doc/sphinx/blob/dd16dd3a4fc766c93cba14cac71fc5285833816e/sphinx/builders/html/__init__.py#L295-L304
