### ISSUE TITLE
jQuery.getQueryParameters is undefined in chrome

### ISSUE THREAD

**Issue by xto** [sphinx-doc/sphinx#1676]
In Sphinx 1.2.3, when using chrome (Version 39.0.2171.99, 64-bit), I'm unable to search through the documentation. I'm not sure if it is related to #1642 since I don't get stuck on "Searching...". I get a Javascript error saying that "undefined is not a function" at line 192 of doctools.js and at line 238 of searchtools.js. Both lines call `$.getQueryParameters`

I also tested with IE 10.0.9200.17183 and the same error happens.

Calling from the browser's console `$.getQueryParameters` returns undefined. What I don't understand is that it works fine in Firefox 33.1.1 and 34.0

I'd be to help with this, though I have no clue why the declaration of `getQueryParameters` is completely ignored by Chrome and IE.

**Comment by shimizukawa** [comment]
I can't reproduce the behavior on my browsers. I suspect that `$` variable was used for another JS library in your sphinx documentation. Could you attach a small source & html example?

**Comment by xto** [comment]
Thanks to you, I figured out the issue. I'm using `sphinxcontrib-images` and it is including jQuery again, undoing the work done by `doctools.js` and `searchtools.js`.

Since the issue is caused by a plugin, I'll close the issue.

Thanks!
